#!/usr/bin/env python3
import sympy as s, json, pathlib
# B6 symbolic invariant search: one global projection law, no physics claim.
t=s.symbols('t', real=True)
x=2*s.cos(t); y=2*s.sin(t)
identities={
 "master_circle":s.simplify(x**2+y**2),
 "polar_cos_circle":s.expand((s.symbols('X')-1)**2+s.symbols('Y')**2),
}
# Special exact events generated by theta=pi/n
events={}
for n in range(3,13):
 a=s.pi/n
 events[f"pi/{n}"]={"2cos":str(s.simplify(2*s.cos(a))),"2sin":str(s.simplify(2*s.sin(a)))}
# Golden rotation: characteristic polynomial of 2cos(pi/5)
z=s.simplify(2*s.cos(s.pi/5))
u=s.symbols('u')
minpoly_phi=s.minpoly(z,u)
# diagonal
q=s.simplify(2*s.cos(s.pi/4)); minpoly_q=s.minpoly(q,u)
# sqrt3
r=s.simplify(2*s.cos(s.pi/6)); minpoly_r=s.minpoly(r,u)
out={"CEREBRON_VERSION":"C42.1","campaign":"SPHERE-DOR-B6-SYMBOLIC","global_invariant":"x^2+y^2=4 for x=2cos(t), y=2sin(t)","special_events":events,"minimal_polynomials":{"2cos(pi/5)":str(minpoly_phi),"2cos(pi/4)":str(minpoly_q),"2cos(pi/6)":str(minpoly_r)},"structural_finding":"phi, sqrt(2), sqrt(3) are algebraic spectral values of the single family 2cos(pi/n); pi parametrizes orientation/period rather than lying in the [-2,2] amplitude range.","novelty_status":"This unification is mathematically exact but built from classical trigonometric/cyclotomic facts; no new theorem yet.","next":"B7 generalize 2cos(pi/n) via roots of unity/Chebyshev polynomials and test whether circle composition yields a nonclassical invariant."}
pathlib.Path("artifacts").mkdir(exist_ok=True);pathlib.Path("artifacts/sphere-dor-b6.json").write_text(json.dumps(out,indent=2));print(json.dumps(out,indent=2))
