#!/usr/bin/env python3
import cmath,json,math,pathlib
# B11 — exact adjacent-circle intersection operator on a regular n-ring.
# centers c_k=a*exp(2*pi*i*k/n); adjacent nonzero intersections p_k=c_k+c_{k+1}.
# Thus p=(I+P)c. Fourier eigenvalues mu_j=1+exp(2*pi*i*j/n).
rows=[]
for n in range(3,31):
    mu=[]
    for j in range(n):
        z=1+cmath.exp(2j*math.pi*j/n)
        mu.append({"j":j,"abs":abs(z),"phase":cmath.phase(z)})
    lam=2*math.cos(math.pi/n)
    # principal regular-polygon mode: one iteration = scale lambda_n + rotate pi/n
    rows.append({"n":n,"lambda":lam,"rotation_per_iteration_rad":math.pi/n,
                 "principal_mu_abs":mu[1]["abs"],
                 "zero_mode_exists": any(x["abs"]<1e-12 for x in mu)})
special={"n4_sqrt2":2*math.cos(math.pi/4),
         "n5_phi":2*math.cos(math.pi/5),
         "n6_sqrt3":2*math.cos(math.pi/6)}
# iteration law for regular n ring: after m adjacent-intersection operations:
# c^(m)_k = a*lambda_n^m*exp(i(2*pi*k/n + m*pi/n))
out={
"CEREBRON_MODE":"STRUCTURED","CEREBRON_VERSION":"C42.1","ROLE":"C-calculation / A-formalisation",
"TARGET":"Exact iteration law for adjacent intersections of equal circles on a regular angular ring.",
"THEOREM_B11":"Let c_k=a exp(2*pi*i*k/n). The non-origin intersection of circles (c_k,a) and (c_{k+1},a) is p_k=c_k+c_{k+1}. Therefore the intersection operator is A=I+P. On Fourier mode j, mu_j=1+exp(2*pi*i*j/n)=2 cos(pi*j/n) exp(i*pi*j/n), up to the sign convention when cos is negative.",
"REGULAR_MODE_ITERATION":"c_k^(m)=a*[2 cos(pi/n)]^m exp(i[2*pi*k/n + m*pi/n]).",
"CLOSURE_ORIENTATION":"orientation closes modulo 2*pi after m=2n iterations; modulo unlabeled n-gon symmetry, one step is already a half-sector shift and two steps restore vertex-sector alignment.",
"SPECTRAL_MAGNITUDES":"|mu_j|=2|cos(pi*j/n)|.",
"EVEN_N_NULL_MODE":"For even n, j=n/2 gives mu_j=0: the alternating Fourier mode is annihilated in one application.",
"SPECIAL":special,"SCAN":rows,
"STATUS":{"intersection_identity":"V exact","operator_spectrum":"K/V known circulant spectral algebra verified for construction","novelty":"NOT ESTABLISHED"},
"RESIDUAL":"Determine whether the user's historical 16-circle construction is generated by this operator or a different composition rule. Do not identify them without reconstruction.",
"NEXT_DECISIVE_TEST":"B12 reconstruct exact 16-circle/8-pair rule from constraints and compare its observed geometry against A=I+P without fitting."
}
pathlib.Path("artifacts").mkdir(exist_ok=True)
pathlib.Path("artifacts/sphere-dor-b11.json").write_text(json.dumps(out,indent=2))
print(json.dumps(out,indent=2))
