import json,hashlib,pathlib
OUT=pathlib.Path("artifacts/reality_gap_v13.json");OUT.parent.mkdir(exist_ok=True)
gaps=[
{"id":"G01","source":"RT04","priority":"P0","gap":"UNCERTAINTY_NOT_CALIBRATED","action":"Replace assumed Monte Carlo distributions with traceable empirical or authoritative uncertainty data.","closure":"Every sampled parameter has source, population/context, units, distribution fit or bounded interval, version and SHA.","target":"S8_INPUT_CALIBRATION"},
{"id":"G02","source":"RT05","priority":"P0","gap":"DYNAMICS_FIDELITY","action":"Build Earth-centered propagation with rotation, winds/atmosphere interface, staging and guidance state integration; compare against trusted reference cases.","closure":"Reference-case residuals within declared tolerances and sensitivity report reproduced independently.","target":"S7_REPRODUCED"},
{"id":"G03","source":"RT02","priority":"P0","gap":"COMMON_DEPENDENCIES","action":"Obtain an external reference implementation or independently sourced dataset not derived from the same constants/code path.","closure":"Provenance graph demonstrates independent origin and comparison passes predefined tolerance.","target":"S7_INDEPENDENT_REFERENCE"},
{"id":"G04","source":"RT01","priority":"P1","gap":"NO_HARDWARE_EVIDENCE","action":"Define bench/HIL test plan for sensors, guidance interfaces and representative propulsion/structural inputs without claiming flight qualification.","closure":"Signed test record, calibration chain, raw measurements, uncertainty budget, artifact SHA and reproducible reduction.","target":"S4_HIL_TO_S5_SUBSYSTEM"},
{"id":"G05","source":"RT07","priority":"P1","gap":"FDIR_UNVALIDATED","action":"Exercise failure policy against injected sensor/actuator faults in HIL or validated simulator.","closure":"Detection latency, false-positive rate, missed-detection rate and safe-state behavior meet frozen acceptance criteria.","target":"S4_HIL"},
{"id":"G06","source":"RT03","priority":"P2","gap":"OPTIMUM_NOT_PROVEN","action":"Compare grid/local search with at least one distinct optimizer and multi-start campaign.","closure":"No materially better feasible solution found within frozen search domain and budget; result remains bounded, not global proof.","target":"SEARCH_CONFIDENCE_ONLY"}]
order={"P0":0,"P1":1,"P2":2};gaps.sort(key=lambda x:(order[x["priority"]],x["id"]))
body={"schema":"CEREBRON_REALITY_GAP_PLANNER_V13","blocking_count":len(gaps),"gaps":gaps,"promotion_policy":{"F72":"BLOCKED_UNTIL_P0_CLOSED_AND_P1_REVIEWED","AFAH":"BLOCKED","S8":"REQUIRES_CALIBRATION_EVIDENCE"},"next_executable":"G02_DYNAMICS_FIDELITY","epistemic":["PLAN_NOT_EVIDENCE","CLOSURE_CRITERIA_FROZEN_BEFORE_TEST","NO_AUTO_PROMOTION","PHYSICAL_TESTS_REQUIRE_REAL_EXTERNAL_EXECUTION"]}
body["sha256"]=hashlib.sha256(json.dumps(body,sort_keys=True,separators=(",",":")).encode()).hexdigest();OUT.write_text(json.dumps(body,indent=2)+"\n");print(json.dumps(body))
