import json,hashlib,pathlib
CYCLE="SPACE-E2E-0001"; SEED=20260923
roles=[(101,"environment_state",{"gravity_m_s2":1.62,"solar_factor":1.0,"terrain_cells":64}),(102,"construction_plan",{"site_cells":8,"modules_planned":4,"construction_units":2}),(103,"lunar_state",{"habitats":2,"population_capacity":8,"power_demand_kw":40}),(104,"mars_state",{"habitats":2,"population_capacity":8,"power_demand_kw":55}),(105,"industrial_state",{"feedstock_kg":1000,"product_kg":700,"waste_kg":300}),(106,"energy_state",{"generation_kw":120,"load_kw":95,"reserve_kw":25}),(107,"robot_state",{"robots":6,"available":5,"maintenance":1}),(108,"resource_state",{"excavated_kg":1500,"usable_kg":900,"tailings_kg":600}),(109,"logistics_state",{"inventory_kg":900,"allocated_kg":600,"reserve_kg":300}),(110,"world_checkpoint",{"subsystems_expected":9,"decision":"OPEN","validated":False})]
out=pathlib.Path("artifacts/space-e2e");out.mkdir(parents=True,exist_ok=True);parent="GENESIS";packets=[]
for slot,(farm,key,payload) in enumerate(roles):
 p={"schema_version":"SPACE_STATE_V1","cycle_id":CYCLE,"producer":farm,"logical_time":slot,"seed":SEED,"parent_sha":parent,"inputs_sha":parent,"status":"PASS","epistemic":"REDUCED_CHAIN_SMOKE_NOT_PHYSICAL_VALIDATION","metrics":{},"events":[],"unknowns":[],"contradictions":[],key:payload}
 canonical=json.dumps(p,sort_keys=True,separators=(",",":")).encode();p["outputs_sha"]=hashlib.sha256(canonical).hexdigest();(out/f"F{farm}.json").write_text(json.dumps(p,indent=2)+"\n");packets.append(p);parent=p["outputs_sha"]
checks={"count_10":len(packets)==10,"same_cycle":len({p['cycle_id'] for p in packets})==1,"same_seed":len({p['seed'] for p in packets})==1,"hash_chain":all(packets[i]['parent_sha']==packets[i-1]['outputs_sha'] for i in range(1,len(packets))),"mass_factory":packets[4]['industrial_state']['feedstock_kg']==packets[4]['industrial_state']['product_kg']+packets[4]['industrial_state']['waste_kg'],"energy_balance":packets[5]['energy_state']['generation_kw']==packets[5]['energy_state']['load_kw']+packets[5]['energy_state']['reserve_kw'],"isru_mass":packets[7]['resource_state']['excavated_kg']==packets[7]['resource_state']['usable_kg']+packets[7]['resource_state']['tailings_kg'],"logistics_mass":packets[8]['logistics_state']['inventory_kg']==packets[8]['logistics_state']['allocated_kg']+packets[8]['logistics_state']['reserve_kg']}
status="PASS" if all(checks.values()) else "FAIL";manifest={"cycle_id":CYCLE,"status":status,"checks":checks,"final_sha":parent,"epistemic":"E2E_HASH_CHAIN_SMOKE_ONLY_NOT_CROSS_REPO_TRANSPORT_NOT_PHYSICAL_VALIDATION"};(out/"manifest.json").write_text(json.dumps(manifest,indent=2)+"\n");print(json.dumps(manifest));raise SystemExit(0 if status=="PASS" else 1)
